services:
  - type: web
    name: audiosessions
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PRIVATE_ZONE_PASSWORD
        value: Julio25
      - key: PORT
        value: 10000
